### ISSUE TITLE
Slurping and barfing changes cursor position

### ISSUE THREAD

**Issue by kindlychung** [guns/vim-sexp#14]
For example:

    (f1 (f2 fC3 f4))

cursor position marked by C. After barfing once to the left, the cursor moves to the left paren:

    (f1 f2 (Cf3 f4))

This is quite annoying compared to paredit in emacs. Is there an option to make the cursor stay where it was? 

Thanks!

**Comment by guns** [comment]
Hello, thanks for reporting!

This is actually a duplicate of #10, which I am planning on nailing down later today. You could add any further suggestions to that thread.
