### ISSUE TITLE
Please add count to ae and ie

### ISSUE THREAD

**Issue by dubiousdavid** [guns/vim-sexp#16]
The ae and ie object selectors would be more useful if you could prepend a count.  BTW, I'm really liking vim-sexp.

**Comment by guns** [comment]
Hello, thanks for reporting!

The `ae` and `ie` text objects are analogous to the builtin `aw` and `iw` objects, which do not accept a count. The `<M-f>` and `<M-b>` motions do accept counts, however, and are probably what you're looking for.

HTH!

**Comment by bpstahlman** [comment]
> The ae and ie object selectors would be more useful if you could prepend a count. BTW, I'm really liking vim-sexp.

@dubiousdavid I've implemented this feature (along with several others) on a fork I'm preparing for an eventual PR: [enhanced-sexp-objects](https://github.com/bpstahlman/vim-sexp/tree/enhanced-sexp-objects) 

Features are mostly documented/working, (though significant code cleanup is still needed). 
Feedback welcome...
